
export type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'ru' | 'nl';

export const TRANSLATIONS: Record<Language, any> = {
  pt: {
    nav: { home: 'Início', wines: 'Vinhos', about: 'O Clube', benefits: 'Benefícios', contact: 'Contato', call: 'LIGUE AGORA' },
    hero: { badge: 'Exclusividade Portuguesa', title: 'A Alma de Portugal Entregue em suas Mãos', desc: 'Uma seleção premium de tintos, brancos, rosés e verdes, escolhidos a dedo nos melhores terroirs de Portugal.', cta1: 'Explorar Coleção', cta2: 'Torne-se Membro' },
    about: { badge: 'Tradição & Exclusividade', title: 'Mais que um Clube, uma Conexão Direta', p1: 'O Porto Wine Club nasceu da paixão pela herança vinícola portuguesa. Localizados em La Nucia, Alicante, servimos como a ponte exclusiva entre as vinícolas mais prestigiadas de Portugal e os apreciadores mais exigentes.', feat1: 'Curadoria de Elite', feat1_desc: 'Apenas rótulos com pontuação superior.', feat2: 'Preço Justo', feat2_desc: 'Sem intermediários. Direto do produtor.', stat1: 'Rótulos Selecionados', stat2: 'Origem Garantida', cta: 'Conheça Nossa História' },
    catalog: { badge: 'Vinhos Premium', title: 'Nossa Seleção Especial', filters: { all: 'Todos', red: 'Tintos', white: 'Brancos', rose: 'Rosés', green: 'Verdes' }, search: 'Buscar...', memberPrice: 'Preço Membro', add: 'Adicionar ao Carrinho', sommelier: 'Fale com nosso Sommelier' },
    benefits: { badge: 'Privilégios do Clube', title: 'A Excelência que você merece, Vantagens que você conquista.', p: 'Fazer parte do Porto Wine Club é garantir o acesso ao que há de mais refinado em Portugal.', item1: 'Entrega Direta', item1_desc: 'Vinhos frescos vindo diretamente de Portugal.', item2: 'Preços Exclusivos', item2_desc: 'Economize até 30% em relação ao mercado.', item3: 'Curadoria', item3_desc: 'Acesso a rótulos raros e edições limitadas.', item4: 'Origem', item4_desc: 'Certificado de autenticidade garantido.', item5: 'Eventos VIP', item5_desc: 'Degustações privadas e visitas exclusivas.', item6: 'Logística Própria', item6_desc: 'Cuidado extremo no transporte das garrafas.', cta_title: 'Pronto para elevar seu paladar?', cta_sub: 'Junte-se à nossa comunidade exclusiva.', cta_btn: 'Assinar Agora' },
    contact: { title: 'Contate um Especialista', badge: 'Envie uma Mensagem', name: 'Nome Completo', email: 'Seu E-mail', subject: 'Assunto', message: 'Sua Mensagem', send: 'Enviar Mensaje', loc: 'Localização', hours: 'Horário', scan: 'Acesso Rápido' },
    cart: { title: 'Seu Carrinho', empty: 'Seu carrinho está vazio', continue: 'Continuar Comprando', subtotal: 'Subtotal', shipping: 'Frete (Grátis p/ Membros)', total: 'Total', checkout: 'Finalizar Compra' },
    testimonials: { title: 'O que dizem nossos membros', t1: 'A qualidade dos vinhos supera todas as expectativas. Uma verdadeira experiência portuguesa em cada garrafa.', t1_author: 'Carlos Mendes', t2: 'A entrega foi rápida e a embalagem impecável. Adorei os vinhos verdes.', t2_author: 'Sophie Dubois', t3: 'Tornar-se membro foi uma das melhores decisões. Os vinhos exclusivos são incríveis.', t3_author: 'James Wright' },
    checkout: { title: 'Finalizar Compra', shipping: 'Dados de Envio', firstName: 'Nome', lastName: 'Sobrenome', email: 'Email', address: 'Endereço', city: 'Cidade', zip: 'CEP', country: 'País', payment: 'Pagamento', proceed: 'Ir para Pagamento', return: 'Voltar à Loja', summary: 'Resumo do Pedido' },
    ageVerification: { title: 'Verificação de Idade', message: 'Você deve ter 18 anos ou mais para entrar.', yes: 'Sim, tenho 18+', no: 'Não, sou menor de 18', fail: 'Você não pode acessar este site.' },
    cookieConsent: { message: 'Nós usamos cookies para melhorar sua experiência.', accept: 'Aceitar' }
  },
  en: {
    nav: { home: 'Home', wines: 'Wines', about: 'The Club', benefits: 'Benefits', contact: 'Contact', call: 'CALL NOW' },
    hero: { badge: 'Portuguese Exclusivity', title: "Portugal's Soul Delivered to Your Hands", desc: 'A premium selection of red, white, rosé, and green wines, handpicked from Portugal’s finest terroirs.', cta1: 'Explore Collection', cta2: 'Become a Member' },
    about: { badge: 'Tradition & Exclusivity', title: 'More than a Club, a Direct Connection', p1: 'Porto Wine Club was born from a passion for Portuguese wine heritage. Located in La Nucia, Alicante, we serve as the exclusive bridge between Portugal’s most prestigious wineries and demanding connoisseurs.', feat1: 'Elite Curation', feat1_desc: 'Only top-rated labels.', feat2: 'Fair Price', feat2_desc: 'No intermediaries. Direct from the producer.', stat1: 'Selected Labels', stat2: 'Guaranteed Origin', cta: 'Our Story' },
    catalog: { badge: 'Premium Wines', title: 'Our Special Selection', filters: { all: 'All', red: 'Reds', white: 'Whites', rose: 'Rosés', green: 'Greens' }, search: 'Search...', memberPrice: 'Member Price', add: 'Add to Cart', sommelier: 'Talk to our Sommelier' },
    benefits: { badge: 'Club Privileges', title: 'The Excellence you deserve, Advantages you earn.', p: 'Being part of Porto Wine Club ensures access to the finest Portugal has to offer.', item1: 'Direct Delivery', item1_desc: 'Fresh wines straight from Portugal to your door.', item2: 'Exclusive Prices', item2_desc: 'Save up to 30% compared to the traditional market.', item3: 'Expert Curation', item3_desc: 'Access to rare labels and limited editions.', item4: 'Guaranteed Origin', item4_desc: 'Authenticity certificate for every bottle.', item5: 'VIP Events', item5_desc: 'Private tastings and exclusive winery visits.', item6: 'Own Logistics', item6_desc: 'Extreme care in transporting your bottles.', cta_title: 'Ready to elevate your palate?', cta_sub: 'Join our exclusive community of enthusiasts.', cta_btn: 'Join Now' },
    contact: { title: 'Contact a Specialist', badge: 'Send a Message', name: 'Full Name', email: 'Your Email', subject: 'Subject', message: 'Your Message', send: 'Send Message', loc: 'Location', hours: 'Opening Hours', scan: 'Quick Access' },
    cart: { title: 'Your Cart', empty: 'Your cart is empty', continue: 'Continue Shopping', subtotal: 'Subtotal', shipping: 'Shipping (Free for Members)', total: 'Total', checkout: 'Checkout' },
    testimonials: { title: 'What our members say', t1: 'The quality of the wines exceeds all expectations. A true Portuguese experience in every bottle.', t1_author: 'Carlos Mendes', t2: 'Delivery was fast and packaging impeccable. I loved the green wines.', t2_author: 'Sophie Dubois', t3: 'Becoming a member was one of the best decisions. The exclusive wines are incredible.', t3_author: 'James Wright' },
    checkout: { title: 'Checkout', shipping: 'Shipping Details', firstName: 'First Name', lastName: 'Last Name', email: 'Email', address: 'Address', city: 'City', zip: 'Zip Code', country: 'Country', payment: 'Payment', proceed: 'Proceed to Payment', return: 'Return to Shop', summary: 'Order Summary' },
    ageVerification: { title: 'Age Verification', message: 'You must be 18 years or older to enter.', yes: 'Yes, I am 18+', no: 'No, I am under 18', fail: 'You cannot enter this site.' },
    cookieConsent: { message: 'We use cookies to improve your experience.', accept: 'Accept' }
  },
  es: {
    nav: { home: 'Inicio', wines: 'Vinos', about: 'El Club', benefits: 'Beneficios', contact: 'Contacto', call: 'LLAMAR AHORA' },
    hero: { badge: 'Exclusividad Portuguesa', title: 'El Alma de Portugal Entregada en sus Manos', desc: 'Una selección premium de tintos, blancos, rosados y verdes, elegidos a mano en los mejores terruños de Portugal.', cta1: 'Explorar Colección', cta2: 'Hacerse Miembro' },
    about: { badge: 'Tradición y Exclusividad', title: 'Más que un Club, una Conexión Directa', p1: 'Porto Wine Club nació de la pasión por la herencia vinícola portuguesa. Ubicados en La Nucía, Alicante, servimos como el puente exclusivo entre las bodegas más prestigiosas de Portugal.', feat1: 'Curaduría de Élite', feat1_desc: 'Solo etiquetas con puntuación superior.', feat2: 'Precio Justo', feat2_desc: 'Sin intermediarios. Directo del productor.', stat1: 'Etiquetas Seleccionadas', stat2: 'Origen Garantizado', cta: 'Conozca Nuestra Historia' },
    catalog: { badge: 'Vinos Premium', title: 'Nuestra Selección Especial', filters: { all: 'Todos', red: 'Tintos', white: 'Blancos', rose: 'Rosados', green: 'Verdes' }, search: 'Buscar...', memberPrice: 'Precio Miembro', add: 'Añadir al Carrito', sommelier: 'Hable con nuestro Sommelier' },
    benefits: { badge: 'Privilegios del Club', title: 'La Excelencia que mereces, Ventajas que conquistas.', p: 'Formar parte del Porto Wine Club es garantizar el acceso a lo más refinado de Portugal.', item1: 'Entrega Directa', item1_desc: 'Vinos frescos directamente desde Portugal.', item2: 'Precios Exclusivos', item2_desc: 'Ahorre hasta un 30% respecto al mercado.', item3: 'Curaduría', item3_desc: 'Acceso a etiquetas raras y ediciones limitadas.', item4: 'Origen', item4_desc: 'Certificado de autenticidad garantizado.', item5: 'Eventos VIP', item5_desc: 'Catas privadas y visitas exclusivas.', item6: 'Logística Propia', item6_desc: 'Cuidado extremo en el transporte.', cta_title: '¿Listo para elevar su paladar?', cta_sub: 'Únase a nuestra comunidad exclusiva.', cta_btn: 'Suscribirse Ahora' },
    contact: { title: 'Contacte a un Especialista', badge: 'Enviar Mensaje', name: 'Nombre Completo', email: 'Su Email', subject: 'Asunto', message: 'Su Mensaje', send: 'Enviar Mensaje', loc: 'Ubicación', hours: 'Horario', scan: 'Acceso Rápido' },
    cart: { title: 'Su Carrito', empty: 'Su carrito está vacío', continue: 'Continuar Comprando', subtotal: 'Subtotal', shipping: 'Envío (Gratis p/ Miembros)', total: 'Total', checkout: 'Finalizar Compra' },
    testimonials: { title: 'Lo que dicen nuestros miembros', t1: 'La calidad de los vinos supera todas las expectativas. Una verdadera experiencia portuguesa en cada botella.', t1_author: 'Carlos Mendes', t2: 'La entrega fue rápida y el embalaje impecable. Me encantaron los vinos verdes.', t2_author: 'Sophie Dubois', t3: 'Ser miembro ha sido una de las mejores decisiones. Los vinos exclusivos son increíbles.', t3_author: 'James Wright' },
    checkout: { title: 'Finalizar Compra', shipping: 'Datos d eEnvío', firstName: 'Nombre', lastName: 'Apellido', email: 'Email', address: 'Dirección', city: 'Ciudad', zip: 'Código Postal', country: 'País', payment: 'Pago', proceed: 'Proceder al Pago', return: 'Volver a la Tienda', summary: 'Resumen del Pedido' },
    ageVerification: { title: 'Verificación de Edad', message: 'Debes tener 18 años o más para entrar.', yes: 'Sí, tengo 18+', no: 'No, soy menor de 18', fail: 'No puedes acceder a este sitio.' },
    cookieConsent: { message: 'Usamos cookies para mejorar su experiencia.', accept: 'Aceptar' }
  },
  fr: {
    nav: { home: 'Accueil', wines: 'Vins', about: 'Le Club', benefits: 'Avantages', contact: 'Contact', call: 'APPELER' },
    hero: { badge: 'Exclusivité Portugaise', title: 'L’Âme du Portugal Livrée Entre Vos Mains', desc: 'Une sélection premium de vins rouges, blancs, rosés et verts, triés sur le volet dans les meilleurs terroirs.', cta1: 'Explorer la Collection', cta2: 'Devenir Membre' },
    about: { badge: 'Tradition & Exclusivité', title: 'Plus qu’un Club, une Connexion Directe', p1: 'Porto Wine Club est né d’une passion pour l’héritage viticole portugais. Situés à La Nucia, Alicante, nous sommes le pont exclusif avec les domaines les plus prestigieux.', feat1: 'Curations d’Élite', feat1_desc: 'Uniquement des étiquettes d’exception.', feat2: 'Prix Juste', feat2_desc: 'Direct du producteur, sans intermédiaire.', stat1: 'Étiquettes Sélectionnées', stat2: 'Origine Garantie', cta: 'Notre Histoire' },
    catalog: { badge: 'Vins Premium', title: 'Notre Sélection Spéciale', filters: { all: 'Tous', red: 'Rouges', white: 'Blancs', rose: 'Rosés', green: 'Verts' }, search: 'Recherche...', memberPrice: 'Prix Membre', add: 'Ajouter au Panier', sommelier: 'Contacter notre Sommelier' },
    benefits: { badge: 'Privilèges du Club', title: 'L’Excellence méritée, les Avantages gagnés.', p: 'Rejoindre Porto Wine Club garantit l’accès au raffinement portugais.', item1: 'Livraison Directe', item1_desc: 'Vins frais en provenance directe du Portugal.', item2: 'Prix Exclusifs', item2_desc: 'Économisez jusqu’à 30% sur le marché.', item3: 'Curations', item3_desc: 'Accès aux bouteilles rares et limitées.', item4: 'Origine', item4_desc: 'Certificat d’authenticité pour chaque bouteille.', item5: 'Événements VIP', item5_desc: 'Dégustations privées et visites exclusives.', item6: 'Logistique Propre', item6_desc: 'Soin extrême lors du transport.', cta_title: 'Prêt à élever votre palais ?', cta_sub: 'Rejoignez notre communauté exclusive.', cta_btn: 'S’abonner Maintenant' },
    contact: { title: 'Contacter un Spécialiste', badge: 'Envoyer un Message', name: 'Nom Complet', email: 'Votre Email', subject: 'Objet', message: 'Votre Message', send: 'Envoyer', loc: 'Emplacement', hours: 'Horaires', scan: 'Accès Rapide' },
    cart: { title: 'Votre Panier', empty: 'Votre panier est vide', continue: 'Continuer les Achats', subtotal: 'Sous-total', shipping: 'Livraison (Gratuite)', total: 'Total', checkout: 'Payer' },
    testimonials: { title: 'Ce que disent nos membres', t1: 'La qualité des vins dépasse toutes les attentes. Une véritable expérience portugaise dans chaque bouteille.', t1_author: 'Carlos Mendes', t2: 'La livraison a été rapide et l’emballage impeccable. J’ai adoré les vins verts.', t2_author: 'Sophie Dubois', t3: 'Devenir membre a été l’une des meilleures décisions. Les vins exclusifs sont incroyables.', t3_author: 'James Wright' },
    checkout: { title: 'Caisse', shipping: 'Détails de Livraison', firstName: 'Prénom', lastName: 'Nom', email: 'Email', address: 'Adresse', city: 'Ville', zip: 'Code Postal', country: 'Pays', payment: 'Paiement', proceed: 'Procéder au Paiement', return: 'Retour à la Boutique', summary: 'Résumé de la Commande' },
    ageVerification: { title: 'Vérification de l\'âge', message: 'Vous devez avoir 18 ans ou plus pour entrer.', yes: 'Oui, j\'ai 18+', no: 'Non, je suis mineur', fail: 'Vous ne pouvez pas accéder à ce site.' },
    cookieConsent: { message: 'Nous utilisons des cookies pour améliorer votre expérience.', accept: 'Accepter' }
  },
  de: {
    nav: { home: 'Startseite', wines: 'Weine', about: 'Der Club', benefits: 'Vorteile', contact: 'Kontakt', call: 'JETZT ANRUFEN' },
    hero: { badge: 'Portugiesische Exklusivität', title: 'Portugals Seele direkt in Ihren Händen', desc: 'Eine erstklassige Auswahl an Rot-, Weiß-, Rosé- und Perlweinen aus den besten Terroirs Portugals.', cta1: 'Kollektion erkunden', cta2: 'Mitglied werden' },
    about: { badge: 'Tradition & Exklusivität', title: 'Mehr als ein Club, eine direkte Verbindung', p1: 'Der Porto Wine Club entstand aus der Leidenschaft für das portugiesische Wein-Erbe. Wir sind die Brücke zu den renommiertesten Weingütern Portugals.', feat1: 'Elite-Kuration', feat1_desc: 'Nur am besten bewertete Etiketten.', feat2: 'Fairer Preis', feat2_desc: 'Keine Zwischenhändler. Direkt vom Erzeuger.', stat1: 'Ausgewählte Weine', stat2: 'Garantierte Herkunft', cta: 'Unsere Geschichte' },
    catalog: { badge: 'Premium-Weine', title: 'Unsere Spezialauswahl', filters: { all: 'Alle', red: 'Rotweine', white: 'Weißweine', rose: 'Roséweine', green: 'Vinhos Verdes' }, search: 'Suchen...', memberPrice: 'Mitgliederpreis', add: 'In den Warenkorb', sommelier: 'Sommelier kontaktieren' },
    benefits: { badge: 'Club-Privilegien', title: 'Exzellenz, die Sie verdienen.', p: 'Die Mitgliedschaft garantiert Zugang zu den feinsten Weinen Portugals.', item1: 'Direktlieferung', item1_desc: 'Frische Weine direkt aus Portugal.', item2: 'Exklusive Preise', item2_desc: 'Bis zu 30% Ersparnis gegenüber dem Handel.', item3: 'Kuration', item3_desc: 'Zugang zu seltenen Jahrgängen.', item4: 'Herkunft', item4_desc: 'Echtheitszertifikat für jede Flasche.', item5: 'VIP-Events', item5_desc: 'Private Verkostungen und Weingut-Besuche.', item6: 'Eigene Logistik', item6_desc: 'Höchste Sorgfalt beim Transport.', cta_title: 'Bereit für höchsten Genuss?', cta_sub: 'Werden Sie Teil unserer exklusiven Community.', cta_btn: 'Jetzt beitreten' },
    contact: { title: 'Spezialisten kontaktieren', badge: 'Nachricht senden', name: 'Name', email: 'E-Mail', subject: 'Betreff', message: 'Nachricht', send: 'Senden', loc: 'Standort', hours: 'Öffnungszeiten', scan: 'Schnellzugriff' },
    cart: { title: 'Warenkorb', empty: 'Warenkorb leer', continue: 'Weiter einkaufen', subtotal: 'Zwischensumme', shipping: 'Versand (Gratis f. Mitglieder)', total: 'Gesamt', checkout: 'Zur Kasse' },
    testimonials: { title: 'Was unsere Mitglieder sagen', t1: 'Die Qualität der Weine übertrifft alle Erwartungen. Ein echtes portugiesisches Erlebnis in jeder Flasche.', t1_author: 'Carlos Mendes', t2: 'Die Lieferung war schnell und die Verpackung tadellos. Ich liebte die grünen Weine.', t2_author: 'Sophie Dubois', t3: 'Mitglied zu werden war eine der besten Entscheidungen. Die exklusiven Weine sind unglaublich.', t3_author: 'James Wright' },
    checkout: { title: 'Kasse', shipping: 'Versanddetails', firstName: 'Vorname', lastName: 'Nachname', email: 'E-Mail', address: 'Adresse', city: 'Stadt', zip: 'PLZ', country: 'Land', payment: 'Zahlung', proceed: 'Zur Zahlung', return: 'Zurück zum Shop', summary: 'Bestellübersicht' },
    ageVerification: { title: 'Altersprüfung', message: 'Sie müssen 18 Jahre oder älter sein, um einzutreten.', yes: 'Ja, ich bin 18+', no: 'Nein, ich bin unter 18', fail: 'Sie können diese Seite nicht betreten.' },
    cookieConsent: { message: 'Wir verwenden Cookies, um Ihre Erfahrung zu verbessern.', accept: 'Akzeptieren' }
  },
  ru: {
    nav: { home: 'Главная', wines: 'Вина', about: 'Клуб', benefits: 'Привилегии', contact: 'Контакты', call: 'ПОЗВОНИТЬ' },
    hero: { badge: 'Португальский Эксклюзив', title: 'Душа Португалии в Ваших Руках', desc: 'Премиальный выбор красных, белых, розовых и зеленых вин из лучших терруаров Португалии.', cta1: 'Коллекция', cta2: 'Стать членом клуба' },
    about: { badge: 'Традиции и Эксклюзив', title: 'Больше чем клуб — прямая связь', p1: 'Porto Wine Club родился из страсти к португальскому виноделию. Мы — ваш эксклюзивный мост к самым престижным винодельням.', feat1: 'Элитный отбор', feat1_desc: 'Только лучшие оценки.', feat2: 'Честная цена', feat2_desc: 'Без посредников. Напрямую от производителя.', stat1: 'Отобранные вина', stat2: 'Гарантия качества', cta: 'Наша история' },
    catalog: { badge: 'Премиальные вина', title: 'Наша подборка', filters: { all: 'Все', red: 'Красные', white: 'Белые', rose: 'Розовые', green: 'Зеленые' }, search: 'Поиск...', memberPrice: 'Цена для членов', add: 'В корзину', sommelier: 'Наш сомелье' },
    benefits: { badge: 'Привилегии клуба', title: 'Совершенство, которого вы достойны.', p: 'Членство в клубе — это доступ к самому изысканному в Португалии.', item1: 'Прямые поставки', item1_desc: 'Вина прямо с португальских кинт.', item2: 'Эксклюзивные цены', item2_desc: 'Экономия до 30% от рыночной цены.', item3: 'Кураторство', item3_desc: 'Доступ к редким и лимитированным винам.', item4: 'Происхождение', item4_desc: 'Сертификат подлинности каждой бутылки.', item5: 'VIP события', item5_desc: 'Закрытые дегустации.', item6: 'Своя логистика', item6_desc: 'Особая забота при доставке.', cta_title: 'Готовы к новым вкусам?', cta_sub: 'Присоединяйтесь к нашему сообществу.', cta_btn: 'Вступить сейчас' },
    contact: { title: 'Связаться с экспертом', badge: 'Написать нам', name: 'Имя', email: 'E-mail', subject: 'Тема', message: 'Сообщение', send: 'Отправить', loc: 'Локация', hours: 'Часы работы', scan: 'QR-код' },
    cart: { title: 'Корзина', empty: 'Корзина пуста', continue: 'За покупками', subtotal: 'Итого', shipping: 'Доставка (Бесплатно)', total: 'Всего', checkout: 'Оформить' },
    testimonials: { title: 'Отзывы наших членов', t1: 'Качество вин превосходит все ожидания. Настоящий португальский опыт в каждой бутылке.', t1_author: 'Carlos Mendes', t2: 'Доставка была быстрой, а упаковка безупречной. Мне очень понравились зеленые вина.', t2_author: 'Sophie Dubois', t3: 'Стать членом клуба было лучшим решением. Эксклюзивные вина просто невероятны.', t3_author: 'James Wright' },
    checkout: { title: 'Оформление', shipping: 'Детали доставки', firstName: 'Имя', lastName: 'Фамилия', email: 'Email', address: 'Адрес', city: 'Город', zip: 'Индекс', country: 'Страна', payment: 'Оплата', proceed: 'К оплате', return: 'Вернуться в магазин', summary: 'Ваш заказ' },
    ageVerification: { title: 'Проверка возраста', message: 'Вам должно быть 18 лет или больше.', yes: 'Да, мне 18+', no: 'Нет, мне меньше 18', fail: 'Вы не можете войти на этот сайт.' },
    cookieConsent: { message: 'Мы используем куки для улучшения вашего опыта.', accept: 'Принять' }
  },
  nl: {
    nav: { home: 'Home', wines: 'Wijnen', about: 'De Club', benefits: 'Voordelen', contact: 'Contact', call: 'BEL NU' },
    hero: { badge: 'Portugese Exclusiviteit', title: 'De Ziel van Portugal in Uw Handen', desc: 'Een premium selectie rode, witte, rosé en groene wijnen, handgeplukt uit de beste terroirs van Portugal.', cta1: 'Ontdek Collectie', cta2: 'Lid Worden' },
    about: { badge: 'Traditie & Exclusiviteit', title: 'Meer dan een Club, een Directe Verbinding', p1: 'Porto Wine Club is ontstaan uit passie voor het Portugese wijnerfgoed. Wij zijn de exclusieve brug naar de meest prestigieuze wijnhuizen.', feat1: 'Elite Selectie', feat1_desc: 'Alleen topgeklasseerde labels.', feat2: 'Eerlijke Prijs', feat2_desc: 'Geen tussenpersonen. Direct van de boer.', stat1: 'Geselecteerde Wijnen', stat2: 'Gegarandeerde Herkomst', cta: 'Ons Verhaal' },
    catalog: { badge: 'Premium Wijnen', title: 'Onze Speciale Selectie', filters: { all: 'Alle', red: 'Rood', white: 'Wit', rose: 'Rosé', green: 'Groen' }, search: 'Zoeken...', memberPrice: 'Ledenprijs', add: 'In Winkelmand', sommelier: 'Sommelier spreken' },
    benefits: { badge: 'Clubvoordelen', title: 'Uitmuntendheid die u verdient.', p: 'Deel uitmaken van Porto Wine Club garandeert toegang tot het beste van Portugal.', item1: 'Directe Levering', item1_desc: 'Verse wijnen direct van de Portugese wijngaard.', item2: 'Exclusieve Prijzen', item2_desc: 'Bespaar tot 30% vergeleken met de winkel.', item3: 'Curatie', item3_desc: 'Toegang tot zeldzame wijnen.', item4: 'Herkomst', item4_desc: 'Echtheidscertificaat voor elke fles.', item5: 'VIP Events', item5_desc: 'Privéproeverijen en exclusieve bezoeken.', item6: 'Eigen Logistiek', item6_desc: 'Uiterste zorg bij het transport.', cta_title: 'Klaar om uw smaak te verrijken?', cta_sub: 'Word lid van onze exclusieve community.', cta_btn: 'Nu Lid Worden' },
    contact: { title: 'Contact met Specialist', badge: 'Bericht Sturen', name: 'Naam', email: 'E-mail', subject: 'Onderwerp', message: 'Bericht', send: 'Verzenden', loc: 'Locatie', hours: 'Openingstijden', scan: 'Sneltoegang' },
    cart: { title: 'Winkelmand', empty: 'Winkelmand is leeg', continue: 'Verder Winkelen', subtotal: 'Subtotaal', shipping: 'Verzending (Gratis)', total: 'Totaal', checkout: 'Afrekenen' },
    testimonials: { title: 'Wat onze leden zeggen', t1: 'De kwaliteit van de wijnen overtreft alle verwachtingen. Een echte Portugese ervaring in elke fles.', t1_author: 'Carlos Mendes', t2: 'De levering was snel en de verpakking onberispelijk. Ik hield van de groene wijnen.', t2_author: 'Sophie Dubois', t3: 'Lid worden was een van de beste beslissingen. De exclusieve wijnen zijn ongelooflijk.', t3_author: 'James Wright' },
    checkout: { title: 'Afrekenen', shipping: 'Verzendgegevens', firstName: 'Voornaam', lastName: 'Achternaam', email: 'E-mail', address: 'Adres', city: 'Stad', zip: 'Postcode', country: 'Land', payment: 'Betaling', proceed: 'Naar Betaling', return: 'Terug naar Winkel', summary: 'Besteloverzicht' },
    ageVerification: { title: 'Leeftijdsverificatie', message: 'Je moet 18 jaar of ouder zijn om binnen te komen.', yes: 'Ja, ik ben 18+', no: 'Nee, ik ben jonger dan 18', fail: 'Je hebt geen toegang tot deze site.' },
    cookieConsent: { message: 'We gebruiken cookies om uw ervaring te verbeteren.', accept: 'Accepteren' }
  }
};
